apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
  labels:
    app: helloworld
spec:
  containers:
  - name: helloworld-container
    image: image-registry.openshift-image-registry.svc:5000/vmorris/hello-openshift
    env:
      # learn about the downward api https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api
    - name: HELLO
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    ports:
    - name: web-pod
      containerPort: 8090
      protocol: TCP
